Transition from CMake to Makefile and added -D arg

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,19 +1,17 @@
 #!/bin/bash
 
-echo "Installing package."
-echo "Making build files."
-
-cmake -S . -B build
-cmake --build build
-
-echo "Installing executables."
-
-sudo cp build/lsa /usr/local/bin/lsa
-sudo cp build/lsall /usr/local/bin/lsa
-
-echo "Installing man files"
-
-cp src/lsall.1 /usr/share/man/man1
-
-echo "Installation done."
-
+{
+    echo -e "\e[33m[*] Installing executables.\e[0m"
+    sudo cp build/lsa /usr/local/bin/lsa
+    sudo cp build/lsall /usr/local/bin/lsall 
+    echo -e "\e[32m[+] Successfully installed executables.\e[0m"
+} || {
+    echo -e "\e[31m[-] Failed executables installation.\e[0m"
+}
+{
+    echo -e "\e[33m[*] Installing man files.\e[0m"
+    sudo cp src/lsall.1 /usr/share/man/man1
+    echo -e "\e[32m[+] Successfully installed man files.\e[0m"
+} || {
+    echo -e "\e[31m[-] Failed man files installation.\e[0m"
+};
